name = "doh-picko"
main = "worker.js"
compatibility_date = "2024-03-03"

[vars]
# You can define global variables here if needed
NODE_ENV = "production"

[[d1_databases]]
binding = "DB"
database_name = "doh_subscription_db"
database_id = "175b738a-c5fd-4e0f-a4de-4fa7e93d599e" # Put your D1 database UUID here
migrations_dir = "migrations"

[[kv_namespaces]]
binding = "KV"
id = "414d7911505f4dddbd6faee06048a202" # Put your KV namespace ID here
